name: build

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: Build and Publish Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nginx-rtmp
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
