name: build

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
