name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/hadolint.yml"
      - Dockerfile
  pull_request:
    paths:
      - ".github/workflows/hadolint.yml"
      - Dockerfile

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-hadolint@v1
