name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"
    outputs:
      release_version: ${{ env.RELEASE_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: ["get-release-version"]
    env:
      IMAGE_NAME: nginx-rtmp
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.get-release-version.outputs.release_version }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
